
def _generate(contents, file=None, mode='w', dry_run=False):
    if dry_run or file is None:
        print(contents)
    else:
        with open(file, mode) as fid:
            fid.write(contents)
    print(f"Successfully created {file}")


def hello_world(args):
    print('Generating a hello_world app')

    CONTENTS = f"""# DO NOT EDIT THIS FILE. It is generated by flaskerize and may be
# overwritten
import os
from flask import Flask, send_from_directory

def create_app():
    app = Flask(__name__)

    # Serve React App
    @app.route('/')
    def serve():
        return 'Hello, Flaskerize!'
    return app

if __name__ == '__main__':
    app = create_app()
    app.run()

    """
    _generate(CONTENTS, file=args.output_name, dry_run=args.dry_run)
    print("Successfully created new app '{}'".format(args.output_name))


def app_from_dir(args):
    """
    Serve files using `send_from_directory`. Note this is less secure than
    from_static_files as anything within the directory can be served.
    """
    print('args = ', args)
    print('Generating an app from static site directory')

    # The routing for `send_from_directory` comes directly from https://stackoverflow.com/questions/44209978/serving-a-create-react-app-with-flask  # noqa
    CONTENTS = f"""# DO NOT EDIT THIS FILE. It is generated by flaskerize and may be
# overwritten

import os
from flask import Flask, send_from_directory


def create_app():
    app = Flask(__name__, static_folder='{args.source}')

    # Serve static site
    @app.route('/', defaults={{'path': ''}})
    @app.route('/<path:path>')
    def serve(path):
        if path != "" and os.path.exists(app.static_folder + path):
            return send_from_directory(app.static_folder, path)
        else:
            return send_from_directory(app.static_folder, 'index.html')
    return app

if __name__ == '__main__':
    app = create_app()
    app.run()

    """
    _generate(CONTENTS, file=args.output_name, dry_run=args.dry_run)
    print("Successfully created new app '{}'".format(args.output_name))


def app(args):
    CONTENTS = """import os
from flask import Flask


def create_app():
    app = Flask(__name__)
    @app.route('/health')
    @app.route('/')
    def serve():
        return 'Well hello there!'
    return app


if __name__ == '__main__':
    app = create_app()
    app.run()

    """
    _generate(CONTENTS, file=args.output_name, dry_run=args.dry_run)
    print("Successfully created new app '{}'".format(args.output_name))


def blueprint(args):
    """
    Static site blueprint
    """
    print('args = ', args)
    print('Generating a blueprint from static site')

    # The routing for `send_from_directory` comes directly from https://stackoverflow.com/questions/44209978/serving-a-create-react-app-with-flask  # noqa
    CONTENTS = f"""# DO NOT EDIT THIS FILE. It is generated by flaskerize and may be
# overwritten

import os
from flask import Blueprint, send_from_directory

site = Blueprint('site', __name__, static_folder='{args.source}')

# Serve static site
@site.route('/', defaults={{'path': ''}})
@site.route('/<path:path>')
def serve(path):
    if path != "" and os.path.exists(site.static_folder + path):
        return send_from_directory(site.static_folder, path)
    else:
        return send_from_directory(site.static_folder, 'index.html')

    """
    _generate(CONTENTS, file=args.output_name, dry_run=args.dry_run)
    print("Successfully created new blueprint '{}'".format(args.output_name))


def wsgi(args):
    from flaskerize.utils import split_file_factory
    print('args = ', args)
    filename, func = split_file_factory(args.source)
    filename = filename.replace('.py', '')

    CONTENTS = f"""# DO NOT EDIT THIS FILE. It is generated by flaskerize and may be
# overwritten

from {filename} import {func}
app = {func}()
    """
    _generate(CONTENTS, file=args.output_name, dry_run=args.dry_run)
    print("Successfully created new wsgi '{}'".format(args.output_name))


def namespace(args):
    """
    Generate a new Flask-RESTplus API Namespace
    """

    CONTENTS = f"""from flask import request, jsonify
from flask_restplus import Namespace, Resource
from flask_accepts import accepts, responds
import marshmallow as ma

api = Namespace('{args.output_name}', description='All things {args.output_name}')


class {args.output_name.title()}:
    '''A super awesome {args.output_name}'''

    def __init__(self, id: int, a_float: float = 42.0, description: str = ''):
        self.id = id
        self.a_float = a_float
        self.description = description


class {args.output_name.title()}Schema(ma.Schema):
    id = ma.fields.Integer()
    a_float = ma.fields.Float()
    description = ma.fields.String(256)

    @ma.post_load
    def make(self, kwargs):
        return {args.output_name.title()}(**kwargs)


@api.route('/')
class {args.output_name.title()}Resource(Resource):
    @accepts(schema={args.output_name.title()}Schema, api=api)
    @responds(schema={args.output_name.title()}Schema)
    def post(self):
        return request.parsed_obj

    @accepts(dict(name='id', type=int, help='ID of the {args.output_name.title()}'), api=api)
    def get(self):
        return {args.output_name.title()}(id=id)

    @accepts(schema={args.output_name.title()}Schema, api=api)
    @responds(schema={args.output_name.title()}Schema)
    def update(self, id, data):
        todo = self.get(id)
        todo.update(data)
        return todo

    @accepts(dict(name='id', type=int, help='ID of the {args.output_name.title()}'), api=api)
    def delete(self, id):
        todo = self.get(id)
        self.todos.remove(todo)

    """
    print(args)
    _generate(CONTENTS, file=args.output_name, dry_run=args.dry_run)


def dockerfile(args):
    print('args = ', args)
    import os
    if os.path.isfile('requirements.txt'):
        req_txt = """COPY requirements.txt /requirements.txt
RUN pip install --install-option="--prefix=/install" -r /requirements.txt"""
    else:
        req_txt = ""
    CONTENTS = f"""FROM python:3.7-alpine as base

FROM base as builder
RUN mkdir /install
WORKDIR /install
{req_txt}
RUN pip install --install-option="--prefix=/install" gunicorn
RUN pip install --install-option="--prefix=/install" flask

FROM base
COPY --from=builder /install /usr/local
COPY . /app
WORKDIR /app

EXPOSE 8080
ENTRYPOINT ["gunicorn", "--bind", "0.0.0.0:8080", "--access-logfile", "-", "--error-logfile", "-", "{args.source}"]

    """
    _generate(CONTENTS, file=args.output_name, dry_run=args.dry_run)
    print("Successfully created new Dockerfile '{}'".format(args.output_name))
    print('Next, run `docker build -t my_app_image .` to build the docker image and '
          'then use `docker run my_app_image -p 127.0.0.1:80:8080` to launch')


# Mapping of keywords to generation functions
a = {
    'hello-world': hello_world, 'hw': hello_world,
    'app': app,
    'dockerfile': dockerfile,
    'wsgi': wsgi,
    'app_from_dir': app_from_dir,
    'blueprint': blueprint, 'bp': blueprint,
    'namespace': namespace, 'ns': namespace
}
