# DO NOT EDIT THIS FILE. It is generated by flaskerize and may be
# overwritten

import os
from flask import Blueprint, send_from_directory

site = Blueprint('site', __name__, static_folder='test/build/')

# Serve static site
@site.route('/', defaults={'path': ''})
@site.route('/<path:path>')
def serve(path):
    if path != "" and os.path.exists(site.static_folder + path):
        return send_from_directory(site.static_folder, path)
    else:
        return send_from_directory(site.static_folder, 'index.html')

    